### ISSUE TITLE
Blank page for unit tests

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#532] opened 2014-11-16 22:55 UTC
Blank page here (in my installation): http://localhost/qcubed3/vendor/qcubed/framework/assets/php/qcubed_unit_tests.php

I've did the change to make it "load without errors":
```php
require_once(__DOCROOT__ . __VENDOR_ASSETS__ . '/lastcraft/simpletest/unit_tester.php');
require_once(__DOCROOT__ . __VENDOR_ASSETS__ . '/lastcraft/simpletest/reporter.php');
```

And I've added this to the composer.json and did the `composer --dev update` command:
```json
        "require-dev": {
                "lastcraft/simpletest": "dev-master"
        },
```

without these changes the page http://localhost/qcubed3/vendor/qcubed/framework/assets/php/qcubed_unit_tests.php whouldn't work with error complains about not found requires for `unit_tester.php` and `reporter.php`.

**Comment by vaibhav-kaushal** [comment] 2015-02-23 09:17
It looks like solved to me but since I do not work on tests much, I'm unsure. Closing this. If the issue is still present, please re-open.

**Closed by vaibhav-kaushal** 2015-02-23 09:17 UTC
Labels: bug
