### ISSUE TITLE
QAutocomplete with ajax fails after validation error

### ISSUE THREAD

**Issue by vakopian** [qcubed/framework#581] opened 2015-01-24 02:48 UTC
See test case below.
Assume `QAutocomplete` is used with ajax and is `Required`. Leave the value empty and click the button to trigger an ajax request that does validation. The error correctly appears next to the autocomplete control. But after than the autocomplete stops working.

Here is the sample code
* sample.php
```php
<?php
	require('includes/configuration/prepend.inc.php');

	class SampleForm extends QForm {
		protected $lstAuto;
		protected $btnSubmit;

		protected function Form_Create() {
			$this->lstAuto = new QAutocomplete($this);
			$this->lstAuto->Name = 'Lang';
			$this->lstAuto->Required = true;
			$this->lstAuto->SetDataBinder("update_autocompleteList");

			$this->btnSubmit = new QButton($this);
			$this->btnSubmit->Text = 'Click Me';
			$this->btnSubmit->CausesValidation = $this->lstAuto;
			$this->btnSubmit->AddAction(new QClickEvent(), new QAjaxAction('btnButton_Click'));
		}

		protected function btnButton_Click($strFormId, $strControlId, $strParameter) {
		}

		protected function update_autocompleteList($strFormId, $strControlId, $strParameter) {
			$this->lstAuto->DataSource = array("c++", "java", "php", "coldfusion", "javascript", "asp", "ruby");
		}

	}

	SampleForm::Run('SampleForm');
?>
```

* sample.tpl.php
```php
<?php require(__CONFIGURATION__ . '/header.inc.php'); ?>

<?php $this->RenderBegin(); ?>
	<p><?php $this->lstAuto->RenderWithName(); ?></p>
	<p><?php $this->btnSubmit->Render(); ?></p>
<?php $this->RenderEnd(); ?>

<?php require(__CONFIGURATION__ . '/footer.inc.php'); ?>
```

**Comment by vakopian** [comment] 2015-02-19 03:33
@spekary - I know you're busy working on alpha 3, but since you did some work on this control before, could you possibly take a look at this bug? I've spent lots of time on this with no result. I would really appreciate your help on this.

**Comment by vaibhav-kaushal** [comment] 2015-02-19 04:09
Which version of QCubed does this happen on? 2.2.3, I assume.

**Comment by vaibhav-kaushal** [comment] 2015-02-19 04:13
Safari shows me this: 
![screenshot 2015-02-19 09 42 52](https://cloud.githubusercontent.com/assets/2824682/6261805/c2b54eac-b81b-11e4-865d-9898e25b7997.png)

**Comment by spekary** [comment] 2015-02-19 07:40
Any javascript error will cause these things to stop working. I think the likely problem is a version change in jQueryUi from the one this was created to work with, to whatever one you are using now. The error indicates that the function being called doesn't exist. There are two functions being called 'data' and 'response'. 'data' is a standard jQuery function, so double check to make sure jQuery is working, but I assume it is or you would have gotten an error earlier. So, the 'response' function is the likely candidate, and if I remember right, I had to tweak QAutocomplete to make it work with a more recent jQueryUI library because of a change in jQuery or jQueryUI. You could try dropping in the alpha3 version of QAutocompleteBase and seeing if that works. I don't think it is very different. You will need the qAutocomplete.js file too. Or, just see the code that it uses to attach the "response" function.

Essentially what is happening is that it attaches a 'response' function to the autocomplete object to be used later. When the autocomplete object asks for data, it calls the 'request' function. The request function then sends its data to the 'response' function. It appears to be having a problem finding the response function in the autocomplete object.

The first thing to try is to change prepareAjaxList to this:

```		protected function prepareAjaxList($dataSource) {
			$list = $dataSource ? JavaScriptHelper::toJsObject($dataSource) : "[]";
			$strJS = sprintf('$j("#%s").data("ui-autocomplete").response(%s);', $this->ControlId, $list);
			QApplication::ExecuteJavaScript($strJS, QJsPriority::High);
		}
```

You see that the newer jQueryUI uses 'ui-autocomplete' as the data repository for the autocomplete data. That might just fix your problem right there. 

I have thought that this whole mechanism is a little convoluted, and was thinking about simplifying it. Datatables also uses this to send its data to the control via an ajax call. I just think there might be an easier, more supportable way to do it.

**Comment by vakopian** [comment] 2015-02-19 17:42
I should have probably given more details about my own debugging and attempts to fix it. Of course I did notice that the `response` function is not found after the validation error. I think this happens because the control is recreated (or updated?) after the validation error without the `response` data.
So I changed the code to attach the `response` closure to a global JS object (e.g. `window`), to allow accessing it after the error. That fixed the `undefined function` issue, but still auto-complete did not work as expected. Most likely because the closure needs the data in the original object to work properly.

I'll try your suggestion with the `prepareAjaxList`.

Just to be clear, I'm using the latest master branch, with jQuery 1.9.1, jquery-migrate, jqueryui 1.9.2, and of course qAutocomplete.js is also included. I do have a pretty large application all working correctly (including autocompletes in many places).

**Comment by vakopian** [comment] 2015-02-19 17:48
the change in `prepareAjaxList` did not help. Firebug still gives the same error:
```
TypeError: $j(...).data(...).response is not a function
```

**Comment by spekary** [comment] 2015-02-19 18:23
If you are saving the response function globally, then you would change the prepareAjaxList function to call that function, wherever it is, with the data. You should set breakpoints at the spot when it calls the "source" method that you give it, and then set a breakpoint in the response function. That is the connecting point. 
1. You give it a function with 'request' and 'response' parameters in the 'source'.
2. Autocomplete calls that function when it needs data.
3. That function should save off the response value somewhere.
4. That function also triggers an autocomplete_search
5. The autocomplete search finds the data, and then calls the saved response value as a function with the data.

**Comment by vakopian** [comment] 2015-02-20 00:47
I have spent hours and hours debugging this in all the places you mentioned.
At the end I think saving the response function globally is not correct, because when it gets called after the validation error, it's still connected to the old context (the one it was originally created on). Objects in that old context are in different states when it gets called, thus the autocomplete menu does not show.

My conclusion is that the hacks that we've done (statring with my very first version of QAutocomplete) to support the "QCubed way" of doing SetDataBinder is just not working for these schenarios. We need to find a better way of hooking up the ajax handlers of this kind of controls to the QCubed back-end.

**Comment by spekary** [comment] 2015-02-20 03:06
Ahh. I didn't realize you were talking only about validation. You are saying it only stops working after validation fails then? If so, then yes, there are some tricky items there to think through:
1. Validation failure causes the whole control to be redrawn.
2. It is *supposed* to also redraw the javascript that connects the autocomplete functionality when this happens. There are some tricky issues there as it depends on what object is getting the "autocomplete" function called on it, but essentially if an object is redrawn by ajax, jQueryUI will completely tear down the jQueryUI part, and QCubed has to rebuild it.

Is your validation simply that it is Required, or is there anything more than that? This is a good point, and we should include it in our testing. We need to create a series of UI tests, and I have started that in alpha3.

alpha3 has a significant number of changes in the area of how controls are drawn, redrawn, and what causes a control to completely redraw. However, this particular scenario has not been tested in alpha3.

I just checked in a refactoring of QAutocomplete that simplifies the internals for alpha3. It attaches all the handlers to the qcubed object, so there is no chance of them going away. 

Re: having it do it the 'QCubed' way, the new alpha3 QCubed way is a reasonable way to do it, but not the most efficient. When everything goes through the QFormBase::Run function, there is going to be a delay as the formstate gets recreated. For QAutocomplete, even a half-second delay could be unreasonable. There are other ways to do this. You could create your own .php file that is dedicated to outputting the jSon for your autocomplete, and set it up so that it avoids QCubed. The jQuery UI Autocomplete page has an example of doing that.

Another option is the Twitter typeahead widget. Its not part of Bootstrap proper, but is a separate widget that is quite performant, and includes local caching. It looks complicate to set up, though. That would make a great plugin.

**Comment by vakopian** [comment] 2015-02-20 03:23
@spekary , Yes the problem is only after a validation error, and yes it's just a simple Required (as in the sample code).
I did make some progress on this. As you also mentioned, the whole control gets redrawn after a vlidation error. It turns out the problem is not directly caused by this, but still related to it. When the control is redrawn, as you correctly noted, the javascript also gets redrawn with it - so this works correctly.

However, when vlidation fails the control's `Modified` flag is (correctly) set by the system to make sure the error message shows up. But when our ajax call comes in, that flag is still set, because nothing has reset it yet. So when we reply with our `prepareAjaxList`, not only we execute the response javascript, but we force another redraw (because `Modified` flag is still true). This redraw creates a new object, and leaves our `response` closure orphan.

So one solution is to add a single line at the beginning of `prepareAjaxList`:
```
$this->blnModified = false;
```
This seems to work for my simple test case above, but I'm not sure if it will have other consequencies. Also, I'm not sure if that is the correct place to reset the `Modified` flag. Do you know if there is a more correct place where that flag needs to be reset?
If you guys think this is safe and correct, I'll make a PR.

**Comment by vakopian** [comment] 2015-02-20 03:27
BTW, I prefer [select2](http://select2.github.io/select2/) to typeahead, and I have a wrapper for it for QCubed [QSelect2ListBox](https://github.com/qcubed/QSelect2ListBox). I haven't implemented ajax for it yet, but I'm sure I'll get to it one day (it should be similar to other controls).

**Comment by vakopian** [comment] 2015-02-20 03:58
So it turns out my single line solution does not work in a more complex case. For example if the autocomplete control is a child of another control which was also modified by the validation, then resetting the `Modified` flag on the autocomplete control alone is not enough - when the parent is redrawn the child will also be redrawn. Need to find another solution...

**Comment by vakopian** [comment] 2015-02-20 04:56
I just remembered that the `Modified` flag is not persisted in the FormState, so I was wrong when I said 
> when our ajax call comes in, that flag is still set, because nothing has reset it yet

Something else must be setting the `Modified` flag before the ajax call gets to our control...

**Comment by spekary** [comment] 2015-02-20 06:30
I have been debugging this in alpha3, and I see the problem there too. The issue is that it is trying to reset the control so that it is no longer showing the validation error message. Currently, it does that at the earliest opportunity, which is the next event, whatever that is. In this case, the event is the triggering of the data retrieval. This is complex and I think many bugs might be here. We need to consider whether to delay resetting the validation state of all the controls until the next validating event, instead of just any event. We also need to consider whether to use a different method of entry into the program for data retrieval, rather than the event system. Bottom line, we have to block redrawing the control in the middle of data retrieval, so we definitely need a mechanism to be able to send back only the data, and nothing else even if other drawing is queued up. I will ponder it for a bit.

**Comment by spekary** [comment] 2015-02-20 16:30
I had to sleep :-). I just checked in a fix to this for alpha3 into #613. Some of the code you can use for v2 I think. It involves only calling ResetValidation during an ajax call when the triggering control is also validating. That part I think you can use and should fix your problem for now. It adds the additional step of allowing an exclusive javascript command to execute that blocks all other commands and defers them. Unfortunately, that is tied to the new javascript execution system, so probably not easily used by you, but I don't think you will need it.

**Comment by vakopian** [comment] 2015-02-20 20:08
@spekary - Thank you very much! I made the corresponding fix for current master: #615. It does work for my simple test as well as in my larger application.
I have a small concern because this does change current behaviour - people might be relying on the fact that validation errors are cleared after any action, not just actions that cause validations.
Maybe we should have a flag on the action called `ResetsValidation`, that's true by default, and we can control when creating the action. Thoughts?

**Comment by spekary** [comment] 2015-02-20 20:26
Perhaps, but I think its unlikely, and when you think about it, the new behavior is correct. For example, lets say you have some kind of ajax action triggered on key presses, like you are filtering a list. While you type, would you want all you validation messages to disappear? I don't think so. I think you would want to do some typing, fix problems, then press a button, and then see if the form validates again. In particular, if there are multiple validation errors, and they disappear from some ajax action, you will not know what fields were invalid. You would have to submit to see the error messages again. Would be frustrating for a user.

**Comment by vakopian** [comment] 2015-02-20 21:14
Ok, I agree with your reasonning. Let's merge the PR. If when someone complains we'll hear their reasons and we'll think of a solution then (maybe with a global setting to use the old behaviour or the new one)

**Comment by vakopian** [comment] 2015-02-20 22:56
@spekary could you please review and merge #615 ?

**Closed** 2015-02-21 00:00 UTC
Labels: bug
