### ISSUE TITLE
Decoupling QQNode from the DataGrid and HTML Creation

### ISSUE THREAD

**Issue by spekary** [qcubed/framework#658] opened 2015-03-16 18:20 UTC
Currently, QQNodes have functions like GetDataGridHtml. Database nodes should not be generating html. This is part of the bigger issue of being able to easily specify different controls to do list display and management. Our current system is locked into the QDataGrid, which is slow, and uses a PHP 'eval', which is considered unsafe. It also means having to edit the templates to implement other list types, which could be DataTables, Bootstrap tables, a QDataRepeater subclass, or some other unknown future kind of list.

Some developers have been working around this using separate templates to create entirely different systems of list management. I would like to instead have a way of easily changing the type of control that creates lists at codegen time. This would be similar to the already functioning QModelConnector editor dialog functionality, that would let you right click and specify the type of table, and possibly options on the columns as well.

Similar to the way that controls now create their own connection to database columns, each type of lister would know how to create its own connection to the database columns it is listing.

I know some are eager to see 3.0 get released, so I will be working on this as a 3.1 addition, or perhaps a 3.0.1 addition. The problem is that I think this is critical to being able to have Bootstrap codegen ability.

**Comment by vakopian** [comment] 2015-03-16 22:31
I completely agree that `GetDataGridHtml` does not belong in `QQNodes`.
I've also advocated for deprecating `QDataGrid` altogether (because of the template/eval system) in favor of `QSimpleTable`. Do you guys think we could move in that direction? Or are people really attached to their `QDataGrid`'s, and if so what functionality makes it preferable to `QSimpleTable`.

**Comment by spekary** [comment] 2015-03-17 03:48
QSimpleTable is not yet built out to do sorting and filtering like QDataGrid. Datatables can do that, and in general I like data tables, but it has some limitations as well, so we can't completely rely on it for basic data table generation. I am thinking about a layered approach, with the object generating its own connection code. So, there would be a QDataGrid like thing based on QSimpleTable.

**Comment by vaibhav-kaushal** [comment] 2015-03-17 09:05
I am using QDataGrids quite a bit here. I think they should stay but I am in favour of the decoupling of QQNode with QDataGrids. It is a bit messy right now. But I guess the power offered by QDataGrids are irreplaceable. The freedom and flexibility is too good for me.

It is bulky but when things get complicated, QDataGrid is where I turn to. There are enough options there. I am in favor of working out another plugin if possible and let that one stay there as well (I guess that is what the original post points to anyway).

**Comment by spekary** [comment] 2015-03-17 15:02
Do you use the QDataGrid filters?

**Comment by vaibhav-kaushal** [comment] 2015-03-17 15:03
Quite a lot. That is what I use them for primarily. Creating a sorting system with tables is otherwise trivial.

From:  Shannon
Reply-To:  qcubed/framework
Date:  Tuesday, 17 March 2015 8:32 pm
To:  qcubed/framework
Cc:  Vaibhav Kaushal
Subject:  Re: [framework] Decoupling QQNode from the DataGrid and HTML Creation (#658)


Do you use the QDataGrid filters?

**Comment by vakopian** [comment] 2015-03-17 19:11
Well, I think that's the problem with `QDataGrid` - it tries to do too much, and does it pretty badly.
`QSimpleTable` as the name indicates was designed to be a simple table, with the goal of delegating the rest of functionality to subclasses (possibly in plugins). This is because sorting/filtering and many other advanced features are much better and easier handled with front-end components such as DataTables. Thus we have the QDataTables plugin. In fact in jqcubed branch I codegen DataTables based controls for all models. This way allows even better filter handling: with QDataGrid you're restricted to only filtering on the columns you have; what if you want to filter on data that's not shown in the table? So again, in jqucbed branch the DataTables generic filter works seamlessly. And, for even more refined filtering, I codegen separate SearchPanel controls that work with the DataTable controls.

The only thing I can think of where QSimpleTable is missing functionality compared to QDataGrid is the ability to (easily) put QControls in table cells. 
@spekary added the QSimpleTableCheckBoxColumn class to do this for checkboxes, but ideally we should be able to do this more generically, for any control type.

**Comment by vaibhav-kaushal** [comment] 2015-03-18 04:54
Couldn’t agree more. QDataGrids are a pain as far as performance is concerned. Though they allow nesting of controls, that is also a painful affair. I guess moving towards QDataTables would be a nice choice as long as we keep QDataGrid for longer so that some new functionality (mostly related to searching could be built) and then we can phase out QDataGrid (or leave it there in case someone needs that)? They are a part of QCubed (do not depend on external libraries) and hence can be great for times if DataTables do not serve purpose.

From:  Vardan Akopian
Reply-To:  qcubed/framework
Date:  Wednesday, 18 March 2015 12:41 am
To:  qcubed/framework
Cc:  Vaibhav Kaushal
Subject:  Re: [framework] Decoupling QQNode from the DataGrid and HTML Creation (#658)


Well, I think that's the problem with QDataGrid - it tries to do too much, and does it pretty badly.
QSimpleTable as the name indicates was designed to be a simple table, with the goal of delegating the rest of functionality to subclasses (possibly in plugins). This is because sorting/filtering and many other advanced features are much better and easier handled with front-end components such as DataTables. Thus we have the QDataTables plugin. In fact in jqcubed branch I codegen DataTables based controls for all models. This way allows even better filter handling: with QDataGrid you're restricted to only filtering on the columns you have; what if you want to filter on data that's not shown in the table? So again, in jqucbed branch the DataTables generic filter works seamlessly. And, for even more refined filtering, I codegen separate SearchPanel controls that work with the DataTable controls.

The only thing I can think of where QSimpleTable is missing functionality compared to QDataGrid is the ability to (easily) put QControls in table cells. 
@spekary added the QSimpleTableCheckBoxColumn class to do this for checkboxes, but ideally we should be able to do this more generically, for any control type.

**Comment by spekary** [comment] 2015-04-09 15:33
>The only thing I can think of where QSimpleTable is missing functionality compared to QDataGrid is the ability to (easily) put QControls in table cells.

You can add a callback column to QSimpleTable, and have the callback draw just like in QDataGrid. There is pretty much no difference between the two for creating controls in the grid.

QSimpleTableCheckBoxColumn is a bit different in its approach, and not the recommended way for putting a custom QControl in a cell.

Actually, I think the main difference is detecting row events. QDataGrid treats the entire row as a QControl and lets you assign events to it. Its flexible, but very inefficient. A QSimpleTable subclass could be made to use the QOnEvent, and put row ids in the tr tag to make something similar.

**Comment by vakopian** [comment] 2015-04-09 18:02
> You can add a callback column to QSimpleTable, and have the callback draw just like in QDataGrid. There is pretty much no difference between the two for creating controls in the grid.

Right, the `QSimpleTableClosureColumn` is kinda meant for that. We should have an example for this just as we have an example of QDataGrid.

> Actually, I think the main difference is detecting row events.

This is where I think (plugin) subclass are more appropriate. For example with `QDataTable` (which is a plugin subclass of `QSimpleTable`), you can use the row events just as easily as with `QDataGrid` and without the overhead
```php
$dtgProducts->AddAction(new QDataTable_RowClickEvent(), new QAjaxControlAction($this, "tableRow_Click"));
```

> A QSimpleTable subclass could be made to use the QOnEvent, and put row ids in the tr tag to make something similar.

For row ids, `QSimpleTable` already has a `GetRowId()` method precisely for that. The subclass just has to implement it.

**Closed** 2015-12-16 05:12 UTC
